services:
  ollama-api:
    image: 'ollama/ollama:latest'
    volumes:
      - 'ollama:/root/.ollama'
    networks:
      - coolify
    ports:
      - '11434:11434'
    healthcheck:
      test:
        - CMD
        - ollama
        - list
      interval: 5s
      timeout: 30s
      retries: 10
  open-webui:
    image: 'ghcr.io/open-webui/open-webui:main'
    volumes:
      - 'open-webui:/app/backend/data'
    networks:
      - coolify
    ports:
      - '3100:8080'
    depends_on:
      - ollama-api
    environment:
      - SERVICE_URL_OLLAMA_8080
      - 'OLLAMA_BASE_URL=http://ollama-api:11434'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8080'
      interval: 5s
      timeout: 30s
      retries: 10
networks:
  coolify:
    external: true
